#!/usr/bin/env bun
// One-off codegen: reads every references/*.json (assumed to be an ABI) and
// emits references/abis.ts with each ABI as `export const <name>Abi = [...] as const`
// so viem can fully infer read/write types from the ABI shape. Files that don't
// parse as a JSON array (or produce an invalid identifier) are skipped with a warning.
//
// Run: bun scripts/gen-abis.ts
// Re-run whenever the JSON ABIs change upstream.

import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const REF_DIR = resolve(ROOT, "references");

const header = [
  "// AUTO-GENERATED by scripts/gen-abis.ts — DO NOT EDIT.",
  "// Refer to: references/*.json.",
  "",
].join("\n");

function toCamelCase(s: string): string {
  return s.replace(/[-_]([a-zA-Z0-9])/g, (_, c: string) => c.toUpperCase());
}

function deriveIdentifier(filename: string): string {
  // Strip `.json`, then strip a trailing `-abi` if present, then camelCase.
  const base = filename.replace(/\.json$/i, "").replace(/-abi$/i, "");
  const camel = toCamelCase(base);
  return `${camel}Abi`;
}

const files = readdirSync(REF_DIR)
  .filter((f) => f.toLowerCase().endsWith(".json"))
  .sort();

const chunks: string[] = [header];
const seen = new Set<string>();
let ok = 0;
let skipped = 0;

for (const file of files) {
  const jsonPath = resolve(REF_DIR, file);
  let abi: unknown;
  try {
    abi = JSON.parse(readFileSync(jsonPath, "utf8"));
  } catch (err) {
    console.warn(`skip ${file}: JSON parse failed (${(err as Error).message})`);
    skipped++;
    continue;
  }
  if (!Array.isArray(abi)) {
    console.warn(`skip ${file}: not a JSON array`);
    skipped++;
    continue;
  }

  const ident = deriveIdentifier(file);
  if (!/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(ident)) {
    console.warn(`skip ${file}: derived identifier "${ident}" is not a valid JS identifier`);
    skipped++;
    continue;
  }
  if (seen.has(ident)) {
    console.warn(`skip ${file}: identifier "${ident}" collides with an earlier file`);
    skipped++;
    continue;
  }
  seen.add(ident);

  chunks.push(
    `export const ${ident} = ${JSON.stringify(abi, null, 2)} as const;`,
  );
  chunks.push("");
  ok++;
}

const outPath = resolve(REF_DIR, "abis.ts");
writeFileSync(outPath, chunks.join("\n"));
console.log(`Wrote ${outPath} (${ok} ABIs, ${skipped} skipped)`);
